/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.util.*;
import javax.swing.*;
//Import all
import pessoa.*;

import services.*;

import tools.*;

import users.*;
/**
 *
 * @author Niquini
 */
public class DentistasAgenda extends javax.swing.JFrame {
    private JanelaAdmin janelaAdmin;
    private JanelaAssistenteAdmin jaa;
    private JanelaUserGeral jug;
    private Vector<Dentista> dent;
    /**
     * Creates new form DentistasAgenda
     */
    public DentistasAgenda() {
        initComponents();
    }
    public DentistasAgenda(JanelaAdmin janelaAdmin, Vector<Dentista> dent){
        this();
        this.janelaAdmin = janelaAdmin;
        this.dent = dent;
    }
    public DentistasAgenda(JanelaAssistenteAdmin jaa, Vector<Dentista> dent){
        this();
        this.jaa = jaa;
        this.dent = dent;
    }
    public DentistasAgenda(JanelaUserGeral jug, Vector<Dentista> dent){
        this();
        this.jug = jug;
        this.dent = dent;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Dent1 = new javax.swing.JButton();
        Dent2 = new javax.swing.JButton();
        Dent3 = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Dent1.setText("One");
        Dent1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dent1ActionPerformed(evt);
            }
        });

        Dent2.setText("Two");
        Dent2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dent2ActionPerformed(evt);
            }
        });

        Dent3.setText("Three");
        Dent3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Dent3ActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Dent1, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(Dent2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Dent3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Cancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Dent1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dent2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Dent3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Cancelar)
                .addGap(0, 188, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Gerenciamento de janelas
        if(janelaAdmin != null){
            janelaAdmin.setVisible(true);
            janelaAdmin.setEnabled(true);
        }
        else if(jaa != null){
            jaa.setVisible(true);
            jaa.setEnabled(true);
        }
        else if(jug != null){
            jug.setVisible(true);
            jug.setEnabled(true);
        }
    }//GEN-LAST:event_formWindowClosed

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // Gerenciamento de janelas
        if(janelaAdmin != null){
            janelaAdmin.setVisible(true);
            janelaAdmin.setEnabled(true);
        }
        else if(jaa != null){
            jaa.setVisible(true);
            jaa.setEnabled(true);
        }
        else if(jug != null){
            jug.setVisible(true);
            jug.setEnabled(true);
        }
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void Dent2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dent2ActionPerformed
        // Mostra agenda de dentista selecionado.
        JOptionPane.showMessageDialog(null, dent.get(1).getAgendaAsString(dent.get(1)));
    }//GEN-LAST:event_Dent2ActionPerformed

    private void Dent3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dent3ActionPerformed
        // Mostra agenda de dentista selecionado.
        JOptionPane.showMessageDialog(null, dent.get(2).getAgendaAsString(dent.get(2)));
    }//GEN-LAST:event_Dent3ActionPerformed

    private void Dent1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Dent1ActionPerformed
        // Mostra agenda de dentista selecionado.
        JOptionPane.showMessageDialog(null, dent.get(0).getAgendaAsString(dent.get(0)));
    }//GEN-LAST:event_Dent1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DentistasAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DentistasAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DentistasAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DentistasAgenda.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DentistasAgenda().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton Dent1;
    private javax.swing.JButton Dent2;
    private javax.swing.JButton Dent3;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
