/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.util.*;
import javax.swing.*;
//Import all
import pessoa.*;

import services.*;

import tools.*;

import users.*;
/**
 *
 * @author Niquini
 */
public class GerarRelatorio extends javax.swing.JFrame {
    private JanelaAdmin janelaAdmin;
    private Vector<Dentista> dent;
    private Vector<Funcionario> fun;
    private ReceberConsultas rc;
    private PagamentoContas pc;
    /**
     * Creates new form GerarRelatorio
     */
    public GerarRelatorio() {
        initComponents();
    }
    public GerarRelatorio(JanelaAdmin   janelaAdmin, Vector<Dentista> dent, 
            Vector<Funcionario> fun, ReceberConsultas rc, PagamentoContas pc){
        this();
        this.janelaAdmin = janelaAdmin;
        this.dent = dent;
        this.fun = fun;
        this.rc = rc;
        this.pc = pc;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Cancelar = new javax.swing.JButton();
        RPagamentos = new javax.swing.JButton();
        RGastos = new javax.swing.JButton();
        RGF = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        RPagamentos.setText("Relatório de pagamentos");
        RPagamentos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RPagamentosActionPerformed(evt);
            }
        });

        RGastos.setText("Relatório de Gastos");
        RGastos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGastosActionPerformed(evt);
            }
        });

        RGF.setText("Relatório de Gastos com funcionários");
        RGF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RGFActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(RPagamentos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(RGastos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(RGF, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(RPagamentos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RGastos)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(RGF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 184, Short.MAX_VALUE)
                .addComponent(Cancelar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // Gerenciamento de janelas
        janelaAdmin.setVisible(true);
        janelaAdmin.setEnabled(true);
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Gerenciamento de janelas
        janelaAdmin.setVisible(true);
        janelaAdmin.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void RPagamentosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RPagamentosActionPerformed
        // Mostra todos os pagamentos de clientes
        String out = "";
        out = rc.getConsultasAsString(rc);
        JOptionPane.showMessageDialog(null, out);
    }//GEN-LAST:event_RPagamentosActionPerformed

    private void RGastosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGastosActionPerformed
        // Mostra todos os gastos por conta
        String out = "";
        for(int i = 0; i < pc.getContasClinica().size(); i++){
                out = out + pc.getValoresConta(pc).get(i) + "\n";
        }
        JOptionPane.showMessageDialog(null, out);

    }//GEN-LAST:event_RGastosActionPerformed

    private void RGFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RGFActionPerformed
        // Mostra todos os gastos com funcionarios
        String out = "";
        for(int i = 0; i < fun.size(); i++){
            out = out + fun.get(i).getNome() + ": \n";
            for(int index = 0; index < fun.get(i).getValorPg().size(); index++){ 
                out = out + fun.get(i).getDatasPg().get(index) +" "+ fun.get(i).getDatasPg().get(index) +" "+ fun.get(i).getDatasPg().get(index) + "\n";
            }
        }
        for(int i = 0; i < dent.size(); i++){
            out = out + dent.get(i).getNome() + ": \n";
            for(int index = 0; index < dent.get(i).getValorPg().size(); index++){ 
                out = out + dent.get(i).getDatasPg().get(index) +" "+ dent.get(i).getDatasPg().get(index) +" "+ dent.get(i).getDatasPg().get(index) + "\n";
            }
        } 
        JOptionPane.showMessageDialog(null, out);
    }//GEN-LAST:event_RGFActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GerarRelatorio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GerarRelatorio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton RGF;
    private javax.swing.JButton RGastos;
    private javax.swing.JButton RPagamentos;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
