/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.util.*;
//Import all
import pessoa.*;

import services.*;

import tools.*;

import users.*;

/**
 *
 * @author Niquini
 */
public class JanelaAdmin extends javax.swing.JFrame {
    private Login login;
    private Vector<Dentista> dent;
    private ReceberConsultas con;
    private PagamentoContas pgc;
    private Vector<Funcionario> fun;
    private Vector<Pessoa> pacientes;
    private Vector<UserGeral> geral;
    private Vector<AssistenteAdm> ass;
    /**
     * Creates new form JanelaAdmin
     */
    public JanelaAdmin() {
        initComponents();
    }
    public JanelaAdmin(Login login, Vector<Dentista> dent, 
            ReceberConsultas con, PagamentoContas pgc, Vector<Funcionario> fun,
            Vector<Pessoa> pacientes,Vector<AssistenteAdm> ass, Vector<UserGeral> geral){
        this();
        this.login = login;
        this.dent = dent;
        this.con = con;
        this.pgc = pgc;
        this.fun = fun;
        this.ass = ass;
        this.geral= geral;
        this.pacientes = pacientes;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        CadastrarUsuario = new javax.swing.JButton();
        Agendas = new javax.swing.JButton();
        ReceberConsulta = new javax.swing.JButton();
        FazerPagamentoDeContas = new javax.swing.JButton();
        FolhaDePonto = new javax.swing.JButton();
        PagarSalario = new javax.swing.JButton();
        GerarRelatorio = new javax.swing.JButton();
        Sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        CadastrarUsuario.setText("Cadastrar Usuario");
        CadastrarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadastrarUsuarioActionPerformed(evt);
            }
        });

        Agendas.setText("Agendas");
        Agendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AgendasActionPerformed(evt);
            }
        });

        ReceberConsulta.setText("Receber Consulta");
        ReceberConsulta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReceberConsultaActionPerformed(evt);
            }
        });

        FazerPagamentoDeContas.setText("Fazer pagamento de contas");
        FazerPagamentoDeContas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FazerPagamentoDeContasActionPerformed(evt);
            }
        });

        FolhaDePonto.setText("Folha de ponto");
        FolhaDePonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolhaDePontoActionPerformed(evt);
            }
        });

        PagarSalario.setText("Pagar salário");
        PagarSalario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PagarSalarioActionPerformed(evt);
            }
        });

        GerarRelatorio.setText("Gerar relatório");
        GerarRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GerarRelatorioActionPerformed(evt);
            }
        });

        Sair.setText("Sair");
        Sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CadastrarUsuario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Agendas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ReceberConsulta, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(FazerPagamentoDeContas, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addComponent(FolhaDePonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(PagarSalario, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(GerarRelatorio, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Sair, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CadastrarUsuario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Agendas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ReceberConsulta)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FazerPagamentoDeContas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(FolhaDePonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(PagarSalario)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(GerarRelatorio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Sair)
                .addGap(0, 80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Gerenciamento de janelas
        login.setVisible(true);
        login.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void CadastrarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadastrarUsuarioActionPerformed
        // Gerenciamento de janelas
        this.setEnabled(false);
        this.setVisible(false);
        new CadastroUsuario(this, ass, geral).setVisible(true);
    }//GEN-LAST:event_CadastrarUsuarioActionPerformed

    private void SairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SairActionPerformed
        // Gerenciamento de janelas
        login.setVisible(true);
        login.setEnabled(true);
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_SairActionPerformed

    private void AgendasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AgendasActionPerformed
        // Gerenciamento de janelas
        this.setEnabled(false);
        this.setVisible(false);
        new DentistasAgenda(this, dent).setVisible(true);
    }//GEN-LAST:event_AgendasActionPerformed

    private void ReceberConsultaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReceberConsultaActionPerformed
        // Gerenciamento de janelas
        this.setEnabled(false);
        this.setVisible(false);
        new ReceberConsulta(this, con).setVisible(true);
    }//GEN-LAST:event_ReceberConsultaActionPerformed

    private void FazerPagamentoDeContasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FazerPagamentoDeContasActionPerformed
        // Gerenciamento de janelas
        this.setEnabled(false);
        this.setVisible(false);
        new FazerPagamentoDeContas(this, pgc).setVisible(true);
    }//GEN-LAST:event_FazerPagamentoDeContasActionPerformed

    private void FolhaDePontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolhaDePontoActionPerformed
        // Gerenciamento de janelas
        this.setEnabled(false);
        this.setVisible(false);
        new ListFolhaPonto(this, dent, fun).setVisible(true);
    }//GEN-LAST:event_FolhaDePontoActionPerformed

    private void PagarSalarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PagarSalarioActionPerformed
        // Gerenciamento de janelas
        this.setEnabled(false);
        this.setVisible(false);
        new PagarSalario(this, dent, fun).setVisible(true);
    }//GEN-LAST:event_PagarSalarioActionPerformed

    private void GerarRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GerarRelatorioActionPerformed
        // Gerenciamento de janelas
        this.setEnabled(false);
        this.setVisible(false);
        new GerarRelatorio(this, dent, fun, con, pgc).setVisible(true);
    }//GEN-LAST:event_GerarRelatorioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JanelaAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JanelaAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Agendas;
    private javax.swing.JButton CadastrarUsuario;
    private javax.swing.JButton FazerPagamentoDeContas;
    private javax.swing.JButton FolhaDePonto;
    private javax.swing.JButton GerarRelatorio;
    private javax.swing.JButton PagarSalario;
    private javax.swing.JButton ReceberConsulta;
    private javax.swing.JButton Sair;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables
}
