/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;
import java.util.*;
//Import all
import pessoa.*;

import services.*;

import tools.*;

import users.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Niquini
 */
public class PagarSalario2 extends javax.swing.JFrame {
    private PagarSalario pagarSalario;
    private Funcionario fun;
    /**
     * Creates new form PagarSalario2
     */
    public PagarSalario2() {
        initComponents();
    }
    public PagarSalario2(PagarSalario pagarSalario, Funcionario fun){
        this();
        this.pagarSalario = pagarSalario;
        this.fun = fun;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FolhaDePonto = new javax.swing.JButton();
        EfetuarPagamento = new javax.swing.JButton();
        Cancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        FolhaDePonto.setText("Folha de ponto");
        FolhaDePonto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FolhaDePontoActionPerformed(evt);
            }
        });

        EfetuarPagamento.setText("Efetuar pagamento");
        EfetuarPagamento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EfetuarPagamentoActionPerformed(evt);
            }
        });

        Cancelar.setText("Cancelar");
        Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(FolhaDePonto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EfetuarPagamento, javax.swing.GroupLayout.DEFAULT_SIZE, 384, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(Cancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(FolhaDePonto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EfetuarPagamento)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addComponent(Cancelar)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelarActionPerformed
        // Gerenciamento de janelas
        pagarSalario.setVisible(true);
        pagarSalario.setEnabled(true);
        this.setEnabled(false);
        this.setVisible(false);
    }//GEN-LAST:event_CancelarActionPerformed

    private void FolhaDePontoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FolhaDePontoActionPerformed
        // Mostra folha de ponto de funcionario selecionado na tela anterior:
        JOptionPane.showMessageDialog(null, fun.getFolhaPontoAsString(fun));
    }//GEN-LAST:event_FolhaDePontoActionPerformed

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
        // Gerenciamento de janelas
        pagarSalario.setVisible(true);
        pagarSalario.setEnabled(true);
    }//GEN-LAST:event_formWindowClosed

    private void EfetuarPagamentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EfetuarPagamentoActionPerformed
        // Efetua o pagamento do funcionario selecionado na tela anterior.
        String value = JOptionPane.showInputDialog("Valor de pagamento: "); 
        if(!"".equals(value)){
            fun.setValorPg( Double.parseDouble(value));
            String descri = JOptionPane.showInputDialog("Descrissão: ");
            fun.setDesriPG(descri);
            String data = JOptionPane.showInputDialog("Data: ");
            fun.setDatasPg(data);
            String out = "";
            for(int index = 1; index < fun.getValorPg().size(); index++){ 
                out = out + fun.getDatasPg().get(index) +" "+ fun.getValorPg().get(index) +" "+ fun.getDescriPg().get(index) + "\n";
            }
            JOptionPane.showMessageDialog(null, out);
        }
    }//GEN-LAST:event_EfetuarPagamentoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PagarSalario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PagarSalario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PagarSalario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PagarSalario2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PagarSalario2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Cancelar;
    private javax.swing.JButton EfetuarPagamento;
    private javax.swing.JButton FolhaDePonto;
    // End of variables declaration//GEN-END:variables
}
